#! /usr/bin/python3.5

import sys
import os

from new_experiment import * 
from prepare_subexperiment import *
from runcodeml import * 
from runm2a import * 
from runmm2a import * 

path2codeml_pbil = "/beegfs/home/lartillot/othersofts/paml4.8/src/"
path2bayescode_p2chpd = "/home_nfs/lbbe/nlartillot/bayescode/data/"

# input:

data_folder = sys.argv[1]
gene_file = sys.argv[2]
tree_file = sys.argv[3]
exp_folder = sys.argv[4]

taxon_file = "alltaxa"

# make new experiment 
# new_experiment(data_folder, gene_file, taxon_file, tree_file, exp_folder)

with open(gene_file, 'r') as infile:
    ngene = len([line for line in infile])
#
# sub-experiments on original empirical data
# 

emp_folder = exp_folder + "/empirical"

# set up subexp on original_data
# prepare_subexperiment(emp_folder)

# prepare additional runs for multigene

uninfpi50mm2a_options= "-x 1 1100 -nucrates ind -bl ind +G -pi 0.50 -purom 0.5 0.5 -dposom 10 1 -purw 0.5 0.5 -posw 0.5 0.5"
uninfpi10mm2a_options= "-x 1 1100 -nucrates ind -bl ind +G -pi 0.10 -purom 0.5 0.5 -dposom 10 1 -purw 0.5 0.5 -posw 0.5 0.5"
uninfpi02mm2a_options= "-x 1 1100 -nucrates ind -bl ind +G -pi 0.02 -purom 0.5 0.5 -dposom 10 1 -purw 0.5 0.5 -posw 0.5 0.5"
subjpi50mm2a_options= "-x 1 1100 -nucrates ind -bl ind +G -pi 0.50 -purom 0.5 0.5 -dposom 2 1 -purw 0.5 0.5 -posw 0.1 0.1"
subjpi10mm2a_options= "-x 1 1100 -nucrates ind -bl ind +G -pi 0.10 -purom 0.5 0.5 -dposom 2 1 -purw 0.5 0.5 -posw 0.1 0.1"
subjpi02mm2a_options= "-x 1 1100 -nucrates ind -bl ind +G -pi 0.02 -purom 0.5 0.5 -dposom 2 1 -purw 0.5 0.5 -posw 0.1 0.1"

core = 16
nodes = 3

runmm2a(emp_folder, uninfpi50mm2a_options, "uninfpi50mm2a", machine="p2chpd", queue="none", nodes=nodes, core=core, time=24, mem=16, path2batch = emp_folder + "/multigene/", path2run = path2bayescode_p2chpd)

# multigene post pred bash scripts (prepare them already at that step)

runmm2a(emp_folder, "uninfpi50mm2a", machine="p2chpd", queue="none", nodes=nodes, core=core, time=24, mem=16, path2batch = emp_folder + "/multigene/", path2run = path2bayescode_p2chpd)

runppredmm2a(emp_folder, "sharedmm2a", burnin = 500, every = 30, nrep = 1, machine="occigen", queue="none", nodes=nodes, core=core, time=1, mem=16, path2batch = emp_folder + "/multigene/", path2run = path2bayescode_occigen)
runppredmm2a(emp_folder, "shrunkenmm2a", burnin = 500, every = 30, nrep = 1, machine="occigen", queue="none", nodes=nodes, core=core, time=1, mem=16, path2batch = emp_folder + "/multigene/", path2run = path2bayescode_occigen)


